# Generated by Django 6.0.3 on 2026-04-16 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_orders', '0001_initial'),
        ('products', '0003_couponcode_discount_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('publish', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField()),
                ('delivery_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('coupon_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=45, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('coupon_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_orders', to='products.couponcode')),
                ('items', models.ManyToManyField(blank=True, related_name='pending_orders', to='cart_orders.cartitems')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pending_order',
            },
        ),
    ]
