# Generated by Django 6.0.3 on 2026-04-17 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_orders', '0002_pendingorder'),
        ('products', '0004_couponcode_max_discount_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingorder',
            name='coupon_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pending_orders', to='products.couponcode'),
        ),
    ]
