# Generated by Django 6.0.3 on 2026-04-26 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_orders', '0003_alter_pendingorder_coupon_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingorder',
            name='payment_method',
            field=models.CharField(choices=[('Khalti', 'Khalti'), ('Esewa', 'Esewa'), ('COD', 'COD')], default='COD', max_length=6),
        ),
    ]
