# Generated by Django 6.0.3 on 2026-04-26 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_orders', '0004_pendingorder_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingBillingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('publish', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=1)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('street_address', models.CharField(max_length=100)),
                ('apartment_suite_unit', models.CharField(max_length=100)),
                ('town_city', models.CharField(max_length=100)),
                ('state_country', models.CharField(max_length=100)),
                ('postcode_zip', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'shipping_billing_address',
            },
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='priority',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pendingorder',
            name='priority',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pendingorder',
            name='billing_address',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='b_pending_orders', to='cart_orders.shippingbillingaddress', null=True, blank=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pendingorder',
            name='shipping_address',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='s_pending_orders', to='cart_orders.shippingbillingaddress', null=True, blank=True),
            preserve_default=False,
        ),
    ]
