# Generated by Django 6.0.3 on 2026-04-26 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_orders', '0005_shippingbillingaddress_alter_cartitems_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingorder',
            name='billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='b_pending_orders', to='cart_orders.shippingbillingaddress'),
        ),
        migrations.AlterField(
            model_name='pendingorder',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='s_pending_orders', to='cart_orders.shippingbillingaddress'),
        ),
    ]
