# Generated by Django 6.0.3 on 2026-04-28 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_orders', '0007_alter_pendingorder_coupon_code_orderitems_userorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='extra_gateway_data',
            field=models.JSONField(default=dict),
        ),
    ]
