# Generated by Django 6.0.3 on 2026-04-10 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('publish', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, null=True, unique=True)),
                ('image', models.ImageField(upload_to='department-images/')),
            ],
            options={
                'db_table': 'departments',
            },
        ),
        migrations.CreateModel(
            name='VariantName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('publish', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'variant_names',
            },
        ),
        migrations.CreateModel(
            name='Variants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('publish', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='products.variantname')),
            ],
            options={
                'db_table': 'variants',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('publish', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, null=True, unique=True)),
                ('image', models.ImageField(upload_to='product-images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('market_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('short_description', models.CharField(max_length=500)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('information', models.TextField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.departments')),
                ('variants', models.ManyToManyField(blank=True, related_name='products', to='products.variants')),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
