# Generated by Django 6.0.3 on 2026-04-16 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_couponcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponcode',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
