# Generated by Django 6.0.3 on 2026-04-17 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_couponcode_discount_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponcode',
            name='max_discount_percentage',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
