# Generated by Django 6.0.3 on 2026-04-26 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_couponcode_max_discount_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponcode',
            name='priority',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='departments',
            name='priority',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='priority',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='variantname',
            name='priority',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='variants',
            name='priority',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
